app:
  replicas: 6
  env: prod
  container:
    image: bhanu/ui
  computerc:
    limits:
      cpu: 4
      memory: 16Gi
    requests: 
      cpu: 4
      memory: 16Gi

hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 4
  cpuuti: 50

config:
  name: config.yaml
  data:
    timeout: 2s
    logfile: /app/var/log.txt
    ip: 120.21.31.10
    name: ui-prod

config-xml:
  name: app.xml